### ISSUE TITLE
[Bug]: OTP input height/alignment

### ISSUE THREAD

**Issue by dreftas** [afsakar/filament-otp-login#12]
### What happened?

Is it just me, or height of OTP inputs is slightly too big ? Or just entered input not centered correctly ?

![image](https://github.com/user-attachments/assets/1b092ba8-d639-4867-9c67-6b64bb77fc41)
![image](https://github.com/user-attachments/assets/2640b7c0-fd41-4763-b5ed-ba9b82aa8aba)

### How to reproduce the bug

Just simply login with OTP login. Enter numbers in input. You should see that entered numbers is not in the center of the box.

### Package Version

1.3.5

### PHP Version

8.3

### Laravel Version

11

**Comment by afsakar** [comment]
This is not a bug, it's just css problems. It is not something that will affect the operation or functioning of the plugin.
