### ISSUE TITLE
[Bug]: Logged in without entering the OTP by clicking the back button then reload.

### ISSUE THREAD

**Issue by koppa53** [afsakar/filament-otp-login#5]
### What happened?

I'm encountering a bug this plugin. When I use the plugin, the OTP (One-Time Password) functionality works fine. However, if I click the back button back to login page without entering the OTP and then reload the page, I am redirected to the dashboard page and find that I am already logged in.

### How to reproduce the bug

Click the back button back to login page without entering the OTP and then reload the page.

### Package Version

1.3.0

### PHP Version

8.3.3

### Laravel Version

11.10.0

### Which operating systems does with happen with?

Windows

**Comment by afsakar** [comment]
Thank you very much for your feedback. I think something was broken in the previous PR and I just fixed it. You can check by installing v1.3.1.
