### ISSUE TITLE
[Bug]: Firefox paste of OTP code unreliable; typing code works fine

### ISSUE THREAD

**Issue by alex-r-redfern** [afsakar/filament-otp-login#6]
### What happened?

When keying in a code manually, the `handleInput` call in the otp-input.blade.php updates the component's state for each key-press, resulting in this.state having the full OTP key by the end of the last number.

When pasting in a code, this is not triggered: Pasting in without previously entering any keypresses results in an exception in vendor/afsakar/filament-otp-login/src/Filament/Pages/Login.php on line 112 as the array key 'otp' is undefined.
If you type in 123456, then remove them all to empty then paste, the 'otp' key is 123456 not the key pasted.

This does not affect Google Chrome, Ungoogled Chromium or Edge

### How to reproduce the bug

Use Firefox (127.0.2) and paste a valid OTP key into the OTP input on login

### Package Version

1.3.1

### PHP Version

8.3.6

### Laravel Version

11.14.0

### Which operating systems does with happen with?

Linux

**Comment by afsakar** [comment]
Hi Alex,

Thank you for your feedback. I fixed the bugs in v1.3.2, you mentioned. You can check it.

Have a good day, best regards.

**Comment by alex-r-redfern** [comment]
Thanks!
